package criu

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-logr/logr/testr"

	"github.com/ai-dynamo/dynamo/deploy/snapshot/internal/types"
)

func TestConfigureInetRemapWritesMapping(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	t.Setenv(InetRemapEnvVar, "")
	if err := ConfigureInetRemap(m, "10.1.4.21", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}

	remapPath := os.Getenv(InetRemapEnvVar)
	if filepath.Dir(remapPath) != workDir {
		t.Fatalf("%s = %q, want file in %q", InetRemapEnvVar, remapPath, workDir)
	}
	if !strings.HasPrefix(filepath.Base(remapPath), "snapshot-inet-remap-") {
		t.Fatalf("%s = %q, want snapshot-inet-remap-* filename", InetRemapEnvVar, remapPath)
	}
	content, err := os.ReadFile(remapPath)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if got, want := string(content), "# generated by Dynamo Snapshot\n10.0.0.11 10.1.4.21\n"; got != want {
		t.Fatalf("remap content = %q, want %q", got, want)
	}
}

func TestConfigureInetRemapUsesUniqueFiles(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	if err := ConfigureInetRemap(m, "10.1.4.21", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap first call: %v", err)
	}
	first := os.Getenv(InetRemapEnvVar)
	if err := ConfigureInetRemap(m, "10.1.4.22", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap second call: %v", err)
	}
	second := os.Getenv(InetRemapEnvVar)
	if first == second {
		t.Fatalf("expected unique remap files, both calls used %q", first)
	}
}

func TestConfigureInetRemapSkipsUnchangedIP(t *testing.T) {
	workDir := t.TempDir()
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        workDir,
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	t.Setenv(InetRemapEnvVar, "stale")
	if err := ConfigureInetRemap(m, "10.0.0.11", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}
	if got := os.Getenv(InetRemapEnvVar); got != "" {
		t.Fatalf("%s = %q, want unset", InetRemapEnvVar, got)
	}
	entries, err := os.ReadDir(workDir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	if len(entries) != 0 {
		t.Fatalf("remap file should not exist, entries: %v", entries)
	}
}

func TestConfigureInetRemapRejectsIPv6(t *testing.T) {
	m := &types.CheckpointManifest{
		CRIUDump: types.CRIUDumpManifest{
			CRIU: types.CRIUSettings{
				LibDir:         "/usr/local/lib/snapshot/criu-plugins",
				TcpEstablished: true,
				WorkDir:        t.TempDir(),
			},
		},
		K8s: types.SourcePodManifest{
			PodIP: "fd00::1",
		},
	}

	err := ConfigureInetRemap(m, "fd00::2", testr.New(t))
	if err == nil {
		t.Fatal("expected IPv6 remap to fail")
	}
	if !strings.Contains(err.Error(), "only supports IPv4") {
		t.Fatalf("expected IPv4-only error, got: %v", err)
	}
}

func TestConfigureInetRemapSkipsWhenTcpEstablishedDisabled(t *testing.T) {
	m := &types.CheckpointManifest{
		K8s: types.SourcePodManifest{
			PodIP: "10.0.0.11",
		},
	}

	if err := ConfigureInetRemap(m, "10.1.4.21", testr.New(t)); err != nil {
		t.Fatalf("ConfigureInetRemap: %v", err)
	}
	if got := os.Getenv(InetRemapEnvVar); got != "" {
		t.Fatalf("%s = %q, want unset", InetRemapEnvVar, got)
	}
}
