package criu

import (
	"fmt"
	"net/netip"
	"os"
	"strings"

	"github.com/go-logr/logr"

	"github.com/ai-dynamo/dynamo/deploy/snapshot/internal/types"
)

const (
	// InetRemapEnvVar points the CRIU INET remap plugin at the restore-time IP map.
	InetRemapEnvVar = "SNAPSHOT_CRIU_INET_REMAP_FILE"
)

// ConfigureInetRemap writes the CRIU plugin manifest for pod IP changes.
func ConfigureInetRemap(
	m *types.CheckpointManifest,
	targetPodIP string,
	log logr.Logger,
) error {
	if err := os.Unsetenv(InetRemapEnvVar); err != nil {
		return fmt.Errorf("failed to clear %s: %w", InetRemapEnvVar, err)
	}

	if !m.CRIUDump.CRIU.TcpEstablished {
		log.V(1).Info("Skipping CRIU INET socket remap: tcpEstablished is disabled")
		return nil
	}

	sourcePodIP := strings.TrimSpace(m.K8s.PodIP)
	targetPodIP = strings.TrimSpace(targetPodIP)
	if sourcePodIP == "" || targetPodIP == "" {
		log.V(1).Info("Skipping CRIU INET socket remap",
			"source_pod_ip_present", sourcePodIP != "",
			"target_pod_ip_present", targetPodIP != "",
		)
		return nil
	}

	sourceAddr, err := netip.ParseAddr(sourcePodIP)
	if err != nil {
		return fmt.Errorf("invalid source pod IP %q in checkpoint manifest: %w", sourcePodIP, err)
	}
	targetAddr, err := netip.ParseAddr(targetPodIP)
	if err != nil {
		return fmt.Errorf("invalid target pod IP %q: %w", targetPodIP, err)
	}
	if sourceAddr == targetAddr {
		log.V(1).Info("Skipping CRIU INET socket remap: pod IP unchanged", "pod_ip", sourcePodIP)
		return nil
	}
	if !sourceAddr.Is4() || !targetAddr.Is4() {
		return fmt.Errorf(
			"CRIU INET socket remap only supports IPv4 pod IPs today: source=%q target=%q",
			sourcePodIP,
			targetPodIP,
		)
	}
	if strings.TrimSpace(m.CRIUDump.CRIU.LibDir) == "" && strings.TrimSpace(os.Getenv("CRIU_LIBS_DIR")) == "" {
		return fmt.Errorf("CRIU INET socket remap requires criu.libDir or CRIU_LIBS_DIR so CRIU can load the Snapshot CRIU plugin")
	}

	remapDir := strings.TrimSpace(m.CRIUDump.CRIU.WorkDir)
	if remapDir == "" {
		remapDir = os.TempDir()
	}
	if err := os.MkdirAll(remapDir, 0755); err != nil {
		return fmt.Errorf("failed to create CRIU INET remap directory: %w", err)
	}

	remapFile, err := os.CreateTemp(remapDir, "snapshot-inet-remap-*.map")
	if err != nil {
		return fmt.Errorf("failed to create CRIU INET remap file: %w", err)
	}
	remapPath := remapFile.Name()
	content := fmt.Sprintf("# generated by Dynamo Snapshot\n%s %s\n", sourceAddr.String(), targetAddr.String())
	if _, err := remapFile.WriteString(content); err != nil {
		_ = remapFile.Close()
		_ = os.Remove(remapPath)
		return fmt.Errorf("failed to write CRIU INET remap file: %w", err)
	}
	if err := remapFile.Close(); err != nil {
		_ = os.Remove(remapPath)
		return fmt.Errorf("failed to close CRIU INET remap file: %w", err)
	}
	if err := os.Setenv(InetRemapEnvVar, remapPath); err != nil {
		return fmt.Errorf("failed to set %s: %w", InetRemapEnvVar, err)
	}

	log.Info("Configured CRIU INET socket remap",
		"source_pod_ip", sourcePodIP,
		"target_pod_ip", targetPodIP,
		"remap_file", remapPath,
	)
	return nil
}
