apiVersion: v1
kind: ConfigMap
metadata:
  name: xpumd-config
  namespace: intel-xpumd
data:
  config.yaml: |
    receivers:
      intelxpu:
        log_level: info
        collection_interval: 5s
        initial_delay: 1s
        timeout: 0
        sampling_interval: 1s
    processors:
      intelxpustatus: {}
    exporters:
      intelxpuinfo: {}
      prometheus:
        endpoint: "0.0.0.0:8080"
    extensions: {}
    service:
      telemetry:
        logs:
          level: info
      pipelines:
        metrics:
          receivers: [intelxpu]
          processors: [intelxpustatus]
          exporters: [intelxpuinfo, prometheus]
