# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dynamo.planner.plugins.proto.v1 import plugin_pb2 as dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dynamo/planner/plugins/proto/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginRegistryStub(object):
    """============================================================================
    PluginRegistry service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginRegistry/Register',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginRegistry/Heartbeat',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginRegistry/Unregister',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginRegistry/ListPlugins',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsResponse.FromString,
                _registered_method=True)


class PluginRegistryServicer(object):
    """============================================================================
    PluginRegistry service
    ============================================================================

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Plugin gracefully announces shutdown; orchestrator immediately removes
        it from active set and clears its HOLD_LAST cache (without waiting for
        missed_heartbeat threshold).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Admin / observability: returns metadata of all registered plugins
        (builtin and user) plus runtime state (circuit breaker, cache age,
        evaluation counts). Authorization typically gated by an admin RBAC
        distinct from plugin Register auth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.PluginRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.PluginRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginRegistry(object):
    """============================================================================
    PluginRegistry service
    ============================================================================

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginRegistry/Register',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginRegistry/Heartbeat',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginRegistry/Unregister',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginRegistry/ListPlugins',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PredictPluginStub(object):
    """============================================================================
    Stage-specific request/response (each stage receives full PipelineContext)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PredictPlugin/Predict',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageResponse.FromString,
                _registered_method=True)


class PredictPluginServicer(object):
    """============================================================================
    Stage-specific request/response (each stage receives full PipelineContext)
    ============================================================================

    """

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.PredictPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.PredictPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictPlugin(object):
    """============================================================================
    Stage-specific request/response (each stage receives full PipelineContext)
    ============================================================================

    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PredictPlugin/Predict',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.PredictStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProposePluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Propose = channel.unary_unary(
                '/dynamo.planner.plugin.v1.ProposePlugin/Propose',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageResponse.FromString,
                _registered_method=True)


class ProposePluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProposePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.ProposePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.ProposePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProposePlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.ProposePlugin/Propose',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ProposeStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReconcilePluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reconcile = channel.unary_unary(
                '/dynamo.planner.plugin.v1.ReconcilePlugin/Reconcile',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageResponse.FromString,
                _registered_method=True)


class ReconcilePluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconcilePluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reconcile': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.ReconcilePlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.ReconcilePlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReconcilePlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.ReconcilePlugin/Reconcile',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ReconcileStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConstrainPluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Constrain = channel.unary_unary(
                '/dynamo.planner.plugin.v1.ConstrainPlugin/Constrain',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageResponse.FromString,
                _registered_method=True)


class ConstrainPluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Constrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConstrainPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Constrain': grpc.unary_unary_rpc_method_handler(
                    servicer.Constrain,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.ConstrainPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.ConstrainPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConstrainPlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Constrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.ConstrainPlugin/Constrain',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ConstrainStageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PluginLifecycleStub(object):
    """============================================================================
    PluginLifecycle service (v10 YAGNI: only Bootstrap + Reset)
    ============================================================================

    Snapshot/Restore are NOT part of this DEP — current code repo lacks the
    mechanism, planner restart goes through Bootstrap to re-fit regression
    (equivalent to cold start). proto3 add new RPC is backward-compatible;
    future PR may add Snapshot/Restore without breaking clients.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bootstrap = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginLifecycle/Bootstrap',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/dynamo.planner.plugin.v1.PluginLifecycle/Reset',
                request_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetRequest.SerializeToString,
                response_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetResponse.FromString,
                _registered_method=True)


class PluginLifecycleServicer(object):
    """============================================================================
    PluginLifecycle service (v10 YAGNI: only Bootstrap + Reset)
    ============================================================================

    Snapshot/Restore are NOT part of this DEP — current code repo lacks the
    mechanism, planner restart goes through Bootstrap to re-fit regression
    (equivalent to cold start). proto3 add new RPC is backward-compatible;
    future PR may add Snapshot/Restore without breaking clients.

    """

    def Bootstrap(self, request, context):
        """Plugin's first-call from orchestrator after Register; one-time priming
        (e.g. load benchmark FPM, warm regression model).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Clear plugin internal state back to pre-Bootstrap; called on config
        reload or test setup/teardown. NOT idempotent in semantics (orchestrator
        guarantees single-call lifecycle).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginLifecycleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.Bootstrap,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetRequest.FromString,
                    response_serializer=dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.planner.plugin.v1.PluginLifecycle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.planner.plugin.v1.PluginLifecycle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginLifecycle(object):
    """============================================================================
    PluginLifecycle service (v10 YAGNI: only Bootstrap + Reset)
    ============================================================================

    Snapshot/Restore are NOT part of this DEP — current code repo lacks the
    mechanism, planner restart goes through Bootstrap to re-fit regression
    (equivalent to cold start). proto3 add new RPC is backward-compatible;
    future PR may add Snapshot/Restore without breaking clients.

    """

    @staticmethod
    def Bootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginLifecycle/Bootstrap',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.BootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.planner.plugin.v1.PluginLifecycle/Reset',
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetRequest.SerializeToString,
            dynamo_dot_planner_dot_plugins_dot_proto_dot_v1_dot_plugin__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
